# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/bulut/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/bulut/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bulut/CLionProjects/siyah1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bulut/CLionProjects/siyah1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/bulut/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/CLion.app/Contents/bin/cmake/mac/bin/cmake" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/bulut/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bulut/CLionProjects/siyah1/CMakeFiles /Users/bulut/CLionProjects/siyah1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bulut/CLionProjects/siyah1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Supervisor

# Build rule for target.
Supervisor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Supervisor
.PHONY : Supervisor

# fast build rule for target.
Supervisor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/build
.PHONY : Supervisor/fast

#=============================================================================
# Target rules for targets named Partner

# Build rule for target.
Partner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Partner
.PHONY : Partner

# fast build rule for target.
Partner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/build
.PHONY : Partner/fast

Partner.o: Partner.cpp.o

.PHONY : Partner.o

# target to build an object file
Partner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/Partner.cpp.o
.PHONY : Partner.cpp.o

Partner.i: Partner.cpp.i

.PHONY : Partner.i

# target to preprocess a source file
Partner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/Partner.cpp.i
.PHONY : Partner.cpp.i

Partner.s: Partner.cpp.s

.PHONY : Partner.s

# target to generate assembly for a file
Partner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/Partner.cpp.s
.PHONY : Partner.cpp.s

Supervisor.o: Supervisor.cpp.o

.PHONY : Supervisor.o

# target to build an object file
Supervisor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/Supervisor.cpp.o
.PHONY : Supervisor.cpp.o

Supervisor.i: Supervisor.cpp.i

.PHONY : Supervisor.i

# target to preprocess a source file
Supervisor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/Supervisor.cpp.i
.PHONY : Supervisor.cpp.i

Supervisor.s: Supervisor.cpp.s

.PHONY : Supervisor.s

# target to generate assembly for a file
Supervisor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/Supervisor.cpp.s
.PHONY : Supervisor.cpp.s

modules/JsonThreadedTCPServer.o: modules/JsonThreadedTCPServer.cpp.o

.PHONY : modules/JsonThreadedTCPServer.o

# target to build an object file
modules/JsonThreadedTCPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/JsonThreadedTCPServer.cpp.o
.PHONY : modules/JsonThreadedTCPServer.cpp.o

modules/JsonThreadedTCPServer.i: modules/JsonThreadedTCPServer.cpp.i

.PHONY : modules/JsonThreadedTCPServer.i

# target to preprocess a source file
modules/JsonThreadedTCPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/JsonThreadedTCPServer.cpp.i
.PHONY : modules/JsonThreadedTCPServer.cpp.i

modules/JsonThreadedTCPServer.s: modules/JsonThreadedTCPServer.cpp.s

.PHONY : modules/JsonThreadedTCPServer.s

# target to generate assembly for a file
modules/JsonThreadedTCPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/JsonThreadedTCPServer.cpp.s
.PHONY : modules/JsonThreadedTCPServer.cpp.s

modules/ThreadedModule.o: modules/ThreadedModule.cpp.o

.PHONY : modules/ThreadedModule.o

# target to build an object file
modules/ThreadedModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/modules/ThreadedModule.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/ThreadedModule.cpp.o
.PHONY : modules/ThreadedModule.cpp.o

modules/ThreadedModule.i: modules/ThreadedModule.cpp.i

.PHONY : modules/ThreadedModule.i

# target to preprocess a source file
modules/ThreadedModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/modules/ThreadedModule.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/ThreadedModule.cpp.i
.PHONY : modules/ThreadedModule.cpp.i

modules/ThreadedModule.s: modules/ThreadedModule.cpp.s

.PHONY : modules/ThreadedModule.s

# target to generate assembly for a file
modules/ThreadedModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/modules/ThreadedModule.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/ThreadedModule.cpp.s
.PHONY : modules/ThreadedModule.cpp.s

modules/ThreadedTCPClient.o: modules/ThreadedTCPClient.cpp.o

.PHONY : modules/ThreadedTCPClient.o

# target to build an object file
modules/ThreadedTCPClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/ThreadedTCPClient.cpp.o
.PHONY : modules/ThreadedTCPClient.cpp.o

modules/ThreadedTCPClient.i: modules/ThreadedTCPClient.cpp.i

.PHONY : modules/ThreadedTCPClient.i

# target to preprocess a source file
modules/ThreadedTCPClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/ThreadedTCPClient.cpp.i
.PHONY : modules/ThreadedTCPClient.cpp.i

modules/ThreadedTCPClient.s: modules/ThreadedTCPClient.cpp.s

.PHONY : modules/ThreadedTCPClient.s

# target to generate assembly for a file
modules/ThreadedTCPClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/ThreadedTCPClient.cpp.s
.PHONY : modules/ThreadedTCPClient.cpp.s

modules/ThreadedTCPServer.o: modules/ThreadedTCPServer.cpp.o

.PHONY : modules/ThreadedTCPServer.o

# target to build an object file
modules/ThreadedTCPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/modules/ThreadedTCPServer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/ThreadedTCPServer.cpp.o
.PHONY : modules/ThreadedTCPServer.cpp.o

modules/ThreadedTCPServer.i: modules/ThreadedTCPServer.cpp.i

.PHONY : modules/ThreadedTCPServer.i

# target to preprocess a source file
modules/ThreadedTCPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/modules/ThreadedTCPServer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/ThreadedTCPServer.cpp.i
.PHONY : modules/ThreadedTCPServer.cpp.i

modules/ThreadedTCPServer.s: modules/ThreadedTCPServer.cpp.s

.PHONY : modules/ThreadedTCPServer.s

# target to generate assembly for a file
modules/ThreadedTCPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/modules/ThreadedTCPServer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/modules/ThreadedTCPServer.cpp.s
.PHONY : modules/ThreadedTCPServer.cpp.s

modules/ThreadedTCPServerKeepPartnerAlive.o: modules/ThreadedTCPServerKeepPartnerAlive.cpp.o

.PHONY : modules/ThreadedTCPServerKeepPartnerAlive.o

# target to build an object file
modules/ThreadedTCPServerKeepPartnerAlive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/modules/ThreadedTCPServerKeepPartnerAlive.cpp.o
.PHONY : modules/ThreadedTCPServerKeepPartnerAlive.cpp.o

modules/ThreadedTCPServerKeepPartnerAlive.i: modules/ThreadedTCPServerKeepPartnerAlive.cpp.i

.PHONY : modules/ThreadedTCPServerKeepPartnerAlive.i

# target to preprocess a source file
modules/ThreadedTCPServerKeepPartnerAlive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/modules/ThreadedTCPServerKeepPartnerAlive.cpp.i
.PHONY : modules/ThreadedTCPServerKeepPartnerAlive.cpp.i

modules/ThreadedTCPServerKeepPartnerAlive.s: modules/ThreadedTCPServerKeepPartnerAlive.cpp.s

.PHONY : modules/ThreadedTCPServerKeepPartnerAlive.s

# target to generate assembly for a file
modules/ThreadedTCPServerKeepPartnerAlive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/modules/ThreadedTCPServerKeepPartnerAlive.cpp.s
.PHONY : modules/ThreadedTCPServerKeepPartnerAlive.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Partner"
	@echo "... Supervisor"
	@echo "... Partner.o"
	@echo "... Partner.i"
	@echo "... Partner.s"
	@echo "... Supervisor.o"
	@echo "... Supervisor.i"
	@echo "... Supervisor.s"
	@echo "... modules/JsonThreadedTCPServer.o"
	@echo "... modules/JsonThreadedTCPServer.i"
	@echo "... modules/JsonThreadedTCPServer.s"
	@echo "... modules/ThreadedModule.o"
	@echo "... modules/ThreadedModule.i"
	@echo "... modules/ThreadedModule.s"
	@echo "... modules/ThreadedTCPClient.o"
	@echo "... modules/ThreadedTCPClient.i"
	@echo "... modules/ThreadedTCPClient.s"
	@echo "... modules/ThreadedTCPServer.o"
	@echo "... modules/ThreadedTCPServer.i"
	@echo "... modules/ThreadedTCPServer.s"
	@echo "... modules/ThreadedTCPServerKeepPartnerAlive.o"
	@echo "... modules/ThreadedTCPServerKeepPartnerAlive.i"
	@echo "... modules/ThreadedTCPServerKeepPartnerAlive.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

