# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.20.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.20.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bulut/CLionProjects/siyah1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bulut/CLionProjects/siyah1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.20.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.20.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bulut/CLionProjects/siyah1/CMakeFiles /Users/bulut/CLionProjects/siyah1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bulut/CLionProjects/siyah1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Supervisor

# Build rule for target.
Supervisor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Supervisor
.PHONY : Supervisor

# fast build rule for target.
Supervisor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/build
.PHONY : Supervisor/fast

#=============================================================================
# Target rules for targets named Partner

# Build rule for target.
Partner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Partner
.PHONY : Partner

# fast build rule for target.
Partner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/build
.PHONY : Partner/fast

PartnerMain.o: PartnerMain.cpp.o
.PHONY : PartnerMain.o

# target to build an object file
PartnerMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/PartnerMain.cpp.o
.PHONY : PartnerMain.cpp.o

PartnerMain.i: PartnerMain.cpp.i
.PHONY : PartnerMain.i

# target to preprocess a source file
PartnerMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/PartnerMain.cpp.i
.PHONY : PartnerMain.cpp.i

PartnerMain.s: PartnerMain.cpp.s
.PHONY : PartnerMain.s

# target to generate assembly for a file
PartnerMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/PartnerMain.cpp.s
.PHONY : PartnerMain.cpp.s

SupervisorMain.o: SupervisorMain.cpp.o
.PHONY : SupervisorMain.o

# target to build an object file
SupervisorMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/SupervisorMain.cpp.o
.PHONY : SupervisorMain.cpp.o

SupervisorMain.i: SupervisorMain.cpp.i
.PHONY : SupervisorMain.i

# target to preprocess a source file
SupervisorMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/SupervisorMain.cpp.i
.PHONY : SupervisorMain.cpp.i

SupervisorMain.s: SupervisorMain.cpp.s
.PHONY : SupervisorMain.s

# target to generate assembly for a file
SupervisorMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/SupervisorMain.cpp.s
.PHONY : SupervisorMain.cpp.s

src/modules/JsonThreadedTCPServer.o: src/modules/JsonThreadedTCPServer.cpp.o
.PHONY : src/modules/JsonThreadedTCPServer.o

# target to build an object file
src/modules/JsonThreadedTCPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/JsonThreadedTCPServer.cpp.o
.PHONY : src/modules/JsonThreadedTCPServer.cpp.o

src/modules/JsonThreadedTCPServer.i: src/modules/JsonThreadedTCPServer.cpp.i
.PHONY : src/modules/JsonThreadedTCPServer.i

# target to preprocess a source file
src/modules/JsonThreadedTCPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/JsonThreadedTCPServer.cpp.i
.PHONY : src/modules/JsonThreadedTCPServer.cpp.i

src/modules/JsonThreadedTCPServer.s: src/modules/JsonThreadedTCPServer.cpp.s
.PHONY : src/modules/JsonThreadedTCPServer.s

# target to generate assembly for a file
src/modules/JsonThreadedTCPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/JsonThreadedTCPServer.cpp.s
.PHONY : src/modules/JsonThreadedTCPServer.cpp.s

src/modules/ThreadedModule.o: src/modules/ThreadedModule.cpp.o
.PHONY : src/modules/ThreadedModule.o

# target to build an object file
src/modules/ThreadedModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/src/modules/ThreadedModule.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/ThreadedModule.cpp.o
.PHONY : src/modules/ThreadedModule.cpp.o

src/modules/ThreadedModule.i: src/modules/ThreadedModule.cpp.i
.PHONY : src/modules/ThreadedModule.i

# target to preprocess a source file
src/modules/ThreadedModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/src/modules/ThreadedModule.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/ThreadedModule.cpp.i
.PHONY : src/modules/ThreadedModule.cpp.i

src/modules/ThreadedModule.s: src/modules/ThreadedModule.cpp.s
.PHONY : src/modules/ThreadedModule.s

# target to generate assembly for a file
src/modules/ThreadedModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/src/modules/ThreadedModule.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/ThreadedModule.cpp.s
.PHONY : src/modules/ThreadedModule.cpp.s

src/modules/ThreadedTCPClient.o: src/modules/ThreadedTCPClient.cpp.o
.PHONY : src/modules/ThreadedTCPClient.o

# target to build an object file
src/modules/ThreadedTCPClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/ThreadedTCPClient.cpp.o
.PHONY : src/modules/ThreadedTCPClient.cpp.o

src/modules/ThreadedTCPClient.i: src/modules/ThreadedTCPClient.cpp.i
.PHONY : src/modules/ThreadedTCPClient.i

# target to preprocess a source file
src/modules/ThreadedTCPClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/ThreadedTCPClient.cpp.i
.PHONY : src/modules/ThreadedTCPClient.cpp.i

src/modules/ThreadedTCPClient.s: src/modules/ThreadedTCPClient.cpp.s
.PHONY : src/modules/ThreadedTCPClient.s

# target to generate assembly for a file
src/modules/ThreadedTCPClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/ThreadedTCPClient.cpp.s
.PHONY : src/modules/ThreadedTCPClient.cpp.s

src/modules/ThreadedTCPServer.o: src/modules/ThreadedTCPServer.cpp.o
.PHONY : src/modules/ThreadedTCPServer.o

# target to build an object file
src/modules/ThreadedTCPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/src/modules/ThreadedTCPServer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/ThreadedTCPServer.cpp.o
.PHONY : src/modules/ThreadedTCPServer.cpp.o

src/modules/ThreadedTCPServer.i: src/modules/ThreadedTCPServer.cpp.i
.PHONY : src/modules/ThreadedTCPServer.i

# target to preprocess a source file
src/modules/ThreadedTCPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/src/modules/ThreadedTCPServer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/ThreadedTCPServer.cpp.i
.PHONY : src/modules/ThreadedTCPServer.cpp.i

src/modules/ThreadedTCPServer.s: src/modules/ThreadedTCPServer.cpp.s
.PHONY : src/modules/ThreadedTCPServer.s

# target to generate assembly for a file
src/modules/ThreadedTCPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/src/modules/ThreadedTCPServer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Partner.dir/build.make CMakeFiles/Partner.dir/src/modules/ThreadedTCPServer.cpp.s
.PHONY : src/modules/ThreadedTCPServer.cpp.s

src/modules/ThreadedTCPServerKeepPartnersAlive.o: src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.o
.PHONY : src/modules/ThreadedTCPServerKeepPartnersAlive.o

# target to build an object file
src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.o
.PHONY : src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.o

src/modules/ThreadedTCPServerKeepPartnersAlive.i: src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.i
.PHONY : src/modules/ThreadedTCPServerKeepPartnersAlive.i

# target to preprocess a source file
src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.i
.PHONY : src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.i

src/modules/ThreadedTCPServerKeepPartnersAlive.s: src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.s
.PHONY : src/modules/ThreadedTCPServerKeepPartnersAlive.s

# target to generate assembly for a file
src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Supervisor.dir/build.make CMakeFiles/Supervisor.dir/src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.s
.PHONY : src/modules/ThreadedTCPServerKeepPartnersAlive.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Partner"
	@echo "... Supervisor"
	@echo "... PartnerMain.o"
	@echo "... PartnerMain.i"
	@echo "... PartnerMain.s"
	@echo "... SupervisorMain.o"
	@echo "... SupervisorMain.i"
	@echo "... SupervisorMain.s"
	@echo "... src/modules/JsonThreadedTCPServer.o"
	@echo "... src/modules/JsonThreadedTCPServer.i"
	@echo "... src/modules/JsonThreadedTCPServer.s"
	@echo "... src/modules/ThreadedModule.o"
	@echo "... src/modules/ThreadedModule.i"
	@echo "... src/modules/ThreadedModule.s"
	@echo "... src/modules/ThreadedTCPClient.o"
	@echo "... src/modules/ThreadedTCPClient.i"
	@echo "... src/modules/ThreadedTCPClient.s"
	@echo "... src/modules/ThreadedTCPServer.o"
	@echo "... src/modules/ThreadedTCPServer.i"
	@echo "... src/modules/ThreadedTCPServer.s"
	@echo "... src/modules/ThreadedTCPServerKeepPartnersAlive.o"
	@echo "... src/modules/ThreadedTCPServerKeepPartnersAlive.i"
	@echo "... src/modules/ThreadedTCPServerKeepPartnersAlive.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

