# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/bulut/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/CLion.app/Contents/bin/cmake/mac/bin/cmake"

# The command to remove a file.
RM = "/Users/bulut/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bulut/CLionProjects/siyah1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bulut/CLionProjects/siyah1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Users/bulut/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/CLion.app/Contents/bin/cmake/mac/bin/cmake" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"/Users/bulut/Library/Application Support/JetBrains/Toolbox/apps/CLion/ch-0/211.7142.21/CLion.app/Contents/bin/cmake/mac/bin/cmake" -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bulut/CLionProjects/siyah1/CMakeFiles /Users/bulut/CLionProjects/siyah1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bulut/CLionProjects/siyah1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named veli

# Build rule for target.
veli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 veli
.PHONY : veli

# fast build rule for target.
veli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/build
.PHONY : veli/fast

#=============================================================================
# Target rules for targets named siyah1

# Build rule for target.
siyah1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 siyah1
.PHONY : siyah1

# fast build rule for target.
siyah1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/build
.PHONY : siyah1/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/main.cpp.s
.PHONY : main.cpp.s

modules/JsonThreadedTCPServer.o: modules/JsonThreadedTCPServer.cpp.o

.PHONY : modules/JsonThreadedTCPServer.o

# target to build an object file
modules/JsonThreadedTCPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/JsonThreadedTCPServer.cpp.o
.PHONY : modules/JsonThreadedTCPServer.cpp.o

modules/JsonThreadedTCPServer.i: modules/JsonThreadedTCPServer.cpp.i

.PHONY : modules/JsonThreadedTCPServer.i

# target to preprocess a source file
modules/JsonThreadedTCPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/JsonThreadedTCPServer.cpp.i
.PHONY : modules/JsonThreadedTCPServer.cpp.i

modules/JsonThreadedTCPServer.s: modules/JsonThreadedTCPServer.cpp.s

.PHONY : modules/JsonThreadedTCPServer.s

# target to generate assembly for a file
modules/JsonThreadedTCPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/JsonThreadedTCPServer.cpp.s
.PHONY : modules/JsonThreadedTCPServer.cpp.s

modules/ThreadedModule.o: modules/ThreadedModule.cpp.o

.PHONY : modules/ThreadedModule.o

# target to build an object file
modules/ThreadedModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/modules/ThreadedModule.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/ThreadedModule.cpp.o
.PHONY : modules/ThreadedModule.cpp.o

modules/ThreadedModule.i: modules/ThreadedModule.cpp.i

.PHONY : modules/ThreadedModule.i

# target to preprocess a source file
modules/ThreadedModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/modules/ThreadedModule.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/ThreadedModule.cpp.i
.PHONY : modules/ThreadedModule.cpp.i

modules/ThreadedModule.s: modules/ThreadedModule.cpp.s

.PHONY : modules/ThreadedModule.s

# target to generate assembly for a file
modules/ThreadedModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/modules/ThreadedModule.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/ThreadedModule.cpp.s
.PHONY : modules/ThreadedModule.cpp.s

modules/ThreadedTCPClient.o: modules/ThreadedTCPClient.cpp.o

.PHONY : modules/ThreadedTCPClient.o

# target to build an object file
modules/ThreadedTCPClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/ThreadedTCPClient.cpp.o
.PHONY : modules/ThreadedTCPClient.cpp.o

modules/ThreadedTCPClient.i: modules/ThreadedTCPClient.cpp.i

.PHONY : modules/ThreadedTCPClient.i

# target to preprocess a source file
modules/ThreadedTCPClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/ThreadedTCPClient.cpp.i
.PHONY : modules/ThreadedTCPClient.cpp.i

modules/ThreadedTCPClient.s: modules/ThreadedTCPClient.cpp.s

.PHONY : modules/ThreadedTCPClient.s

# target to generate assembly for a file
modules/ThreadedTCPClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/ThreadedTCPClient.cpp.s
.PHONY : modules/ThreadedTCPClient.cpp.s

modules/ThreadedTCPServer.o: modules/ThreadedTCPServer.cpp.o

.PHONY : modules/ThreadedTCPServer.o

# target to build an object file
modules/ThreadedTCPServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/modules/ThreadedTCPServer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/ThreadedTCPServer.cpp.o
.PHONY : modules/ThreadedTCPServer.cpp.o

modules/ThreadedTCPServer.i: modules/ThreadedTCPServer.cpp.i

.PHONY : modules/ThreadedTCPServer.i

# target to preprocess a source file
modules/ThreadedTCPServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/modules/ThreadedTCPServer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/ThreadedTCPServer.cpp.i
.PHONY : modules/ThreadedTCPServer.cpp.i

modules/ThreadedTCPServer.s: modules/ThreadedTCPServer.cpp.s

.PHONY : modules/ThreadedTCPServer.s

# target to generate assembly for a file
modules/ThreadedTCPServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/modules/ThreadedTCPServer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siyah1.dir/build.make CMakeFiles/siyah1.dir/modules/ThreadedTCPServer.cpp.s
.PHONY : modules/ThreadedTCPServer.cpp.s

modules/ThreadedTCPServerKeepClientAlive.o: modules/ThreadedTCPServerKeepClientAlive.cpp.o

.PHONY : modules/ThreadedTCPServerKeepClientAlive.o

# target to build an object file
modules/ThreadedTCPServerKeepClientAlive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/modules/ThreadedTCPServerKeepClientAlive.cpp.o
.PHONY : modules/ThreadedTCPServerKeepClientAlive.cpp.o

modules/ThreadedTCPServerKeepClientAlive.i: modules/ThreadedTCPServerKeepClientAlive.cpp.i

.PHONY : modules/ThreadedTCPServerKeepClientAlive.i

# target to preprocess a source file
modules/ThreadedTCPServerKeepClientAlive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/modules/ThreadedTCPServerKeepClientAlive.cpp.i
.PHONY : modules/ThreadedTCPServerKeepClientAlive.cpp.i

modules/ThreadedTCPServerKeepClientAlive.s: modules/ThreadedTCPServerKeepClientAlive.cpp.s

.PHONY : modules/ThreadedTCPServerKeepClientAlive.s

# target to generate assembly for a file
modules/ThreadedTCPServerKeepClientAlive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/modules/ThreadedTCPServerKeepClientAlive.cpp.s
.PHONY : modules/ThreadedTCPServerKeepClientAlive.cpp.s

veli.o: veli.cpp.o

.PHONY : veli.o

# target to build an object file
veli.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/veli.cpp.o
.PHONY : veli.cpp.o

veli.i: veli.cpp.i

.PHONY : veli.i

# target to preprocess a source file
veli.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/veli.cpp.i
.PHONY : veli.cpp.i

veli.s: veli.cpp.s

.PHONY : veli.s

# target to generate assembly for a file
veli.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/veli.dir/build.make CMakeFiles/veli.dir/veli.cpp.s
.PHONY : veli.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... siyah1"
	@echo "... veli"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... modules/JsonThreadedTCPServer.o"
	@echo "... modules/JsonThreadedTCPServer.i"
	@echo "... modules/JsonThreadedTCPServer.s"
	@echo "... modules/ThreadedModule.o"
	@echo "... modules/ThreadedModule.i"
	@echo "... modules/ThreadedModule.s"
	@echo "... modules/ThreadedTCPClient.o"
	@echo "... modules/ThreadedTCPClient.i"
	@echo "... modules/ThreadedTCPClient.s"
	@echo "... modules/ThreadedTCPServer.o"
	@echo "... modules/ThreadedTCPServer.i"
	@echo "... modules/ThreadedTCPServer.s"
	@echo "... modules/ThreadedTCPServerKeepClientAlive.o"
	@echo "... modules/ThreadedTCPServerKeepClientAlive.i"
	@echo "... modules/ThreadedTCPServerKeepClientAlive.s"
	@echo "... veli.o"
	@echo "... veli.i"
	@echo "... veli.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

